### ISSUE TITLE
Spell check not working

### ISSUE THREAD

**Issue by sschmid** [Microsoft/vscode-spell-check#54] opened 2016-10-11 19:27 UTC
Hi,

I just installed the package and it doesn't seem to work for me.
I have the default spell.json in the .vscode folder, markdown and plaintext enabled. Didn't work for a few minutes. I deleted a file in .vscode, then it worked for a few minutes. I added a few words to the ignoreWordsList by clicking "Ignore word" (or similar).
Now it stopped working again and I cannot get it to work. Connection to internet is available. The "Problems" panel is empty.

Am I missing sth?

Thanks

**Comment by seanmcbreen** [comment] 2016-10-12 15:49
No sounds like you are following the right steps - seams odd however - I'll have a look to see if I can repro.

**Comment by drpicox** [comment] 2016-10-14 08:53
Since I have updated VSCode to 1.6.1 is failing also to me.
If I set the language to Spanish it works well, if I set the language to English it seems to do nothing.
Button is at "Spell Enabled", tryied some combination of refresh, close/open, restart, other node versions, no change.

¿Any idea about how to debug this?

**Comment by escamoteur** [comment] 2016-10-15 14:43
Same with me german works, but en does nothing. VSCode 1.6.1

```
{
    "language": "en",
    "ignoreWordsList": [],
    "mistakeTypeToStatus": {
        "Spelling": "Error",
        "Passive voice": "Hint",
        "Complex Expression": "Disable",
        "Hidden Verbs": "Information",
        "Hyphen Required": "Disable",
        "Redundant Expression": "Disable",
        "Did you mean...": "Disable",
        "Repeated Word": "Warning",
        "Missing apostrophe": "Warning",
        "Cliches": "Disable",
        "Missing Word": "Disable",
        "Make I uppercase": "Warning"
    },
    "languageIDs": [
        "markdown",
        "plaintext"
    ],
    "ignoreRegExp": [
        "/\\(.*\\.(jpg|jpeg|png|md|gif|JPG|JPEG|PNG|MD|GIF)\\)/g",
        "/((http|https|ftp|git)\\S*)/g"
    ]
}
```

**Comment by SeanMCB1** [comment] 2016-10-16 16:53
OK I think I have an idea on the issue. - I had a similar repro  I'm not processing some char the right way and crashing (it may well be a change in the engine).  Any chance you can send me the file you used.  You can share privately via sean @ mcbreen.co.nz.

**Comment by drpicox** [comment] 2016-10-16 17:14
Just any text.
To know if there was some kind of configuration error I just created a `dumy.md` with a small sentence with some wrong word.
Example: `helloworld.md`
```
Hola mundlo.
```
In spanish detects mundlo as wrong word. 
```
Hello worlz.
```
In english there are no messages.

**Comment by dragos** [comment] 2016-10-17 14:03
Same here. Code 1.6.1. Nothing, not even in Spanish. Fresh markdown file.

**Comment by giuseppelt** [comment] 2016-10-18 14:59
Devtool reports this error
```
Cannot read property 'message' of undefined: TypeError: Cannot read property 'message' of undefined
    at SpellProvider.provideCodeActions (C:\Users\Giuseppe\.vscode\extensions\seanmcbreen.Spell-0.8.6\out\features\spellProvider.js:83:31)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:24306
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:16079
    at new n.Class.derive._oncancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:12186)
    at Object.l [as asWinJsPromise] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:16042)
    at e.provideCodeActions (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:24260)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:13:482
    at t._withAdapter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:30024)
    at t.$provideCodeActions (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:13:444)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:11474)
```

It seems like the `message` property doesn't exist in `spellProvider.ts`
```typescript
public provideCodeActions(...): vscode.Command[] {
        let diagnostic: vscode.Diagnostic = context.diagnostics[0];
        let match: string[] = diagnostic.message.match(/\[([a-zA-Z0-9\ ]+)\]\ \-/);
```
Maybe something is changed about retrieving diagnostics from the context.

**Comment by seanmcbreen** [comment] 2016-10-19 05:10
A quick update - the issue appears to be upstream in the service.  I've not yet isolated it but for english it simply returns no results whereas it returns results for other languages as pointed out above.  I'll keep digging into it.

**Comment by seanmcbreen** [comment] 2016-10-19 06:10
OK definitely at the service level - I have a very cut down test that returns nothing for the English end-point but returns as expected for German.   Here is the relevant code:

```javascript
function postHTTP() {
    var request = require('request');
    var content = "loook";
    var key = "6dbf22d9ba22f882d017896a1fc0e978a106bed0";

    var enURL = "https://en.service.afterthedeadline.com/checkDocument"
    var deURL = "https://de.service.afterthedeadline.com/checkDocument"

    request({ method: "POST", url: enURL, form: { data: content, key: key } },
        function (error, response, body) {
            console.log(">>>>English Results>>>>>");
            console.log(body);
        }
    );

    request({ method: "POST", url: deURL, form: { data: content, key: key } },
        function (error, response, body) {
            console.log(">>>>German Results:>>>>");
            console.log(body);
        }
    );
}
```

The console gets the following results...

```
>>>>English Results>>>>>
<?xml version='1.0' encoding='us-ascii'?><results />
>>>>German Results:>>>>
<results>
  <error>
    <string>loook</string>
    <description>Spelling</description>
    <precontext></precontext>
    <suggestions>
        <option>Look</option>
        <option>logo</option>
        <option>loco</option>
    </suggestions>
    <type>spelling</type>
    
  </error>
</results>
```

As you can see in the code the body is 100% the same.  I think the best next step is to ask the service owners if something is up on there end.

**Comment by danwulff** [comment] 2016-10-31 17:15
Looks like the google group associated with 'afterthedeadline' is pretty dead: https://groups.google.com/forum/#!forum/atd-developers. Hopefully you hear back from them. (I'm getting the same issue)

**Comment by Dima4ka** [comment] 2016-11-08 19:23
I can confirm the issue on VS Code 1.7.1.
I have copied the `spell.json` file from the "working" workspace (at least it used to work).
No errors or warnings. Almost as if I had no spell mistakes (which I obviously have).

For reference, here is my `spell.json`

```json
{
  "language": "en",
  "ignoreWordsList": [
    "vscode",
    "Markdown",
    "config",
    "languageIDs",
    "alefragnani",
    "Config",
    "json",
    "ignoreWordsList",
    "ignoreRegExp",
    "mistakeTypeToStatus",
    "markdown",
    "excludeFilesList",
    "emph"
  ],
  "mistakeTypeToStatus": {
    "Passive voice": "Hint",
    "Spelling": "Error",
    "Complex Expression": "Warning",
    "Hidden Verbs": "Information",
    "Hyphen Required": "Error",
    "Redundant Expression": "Information",
    "Did you mean...": "Information",
    "Repeated Word": "Error",
    "Missing apostrophe": "Error",
    "Cliches": "Warning",
    "Missing Word": "Warning",
    "Make I uppercase": "Warning"
  },
  "languageIDs": [
    "markdown",
    "latex",
    "plaintext"
  ],
  "ignoreRegExp": [
    "/`(kb.*?)`/g",
    "/(http\\\\S*)/gm",
    "/\\\\(.*.png\\\\)/g",
    "/\\\\(.*.gif\\\\)/g",
    "/\\\\(.*.md\\\\)/g",
    "/\\\\(.*.jpg\\\\)/g",
    "/^((`{3}\\\\s*)(\\\\w+)?(\\\\s*([\\\\w\\\\W]+?)\\\\n*)\\\\2)\\\\n*(?:[^\\\\S\\\\w\\\\s]|$)/gm"
  ]
}
```

**Comment by dwonisch** [comment] 2016-11-20 15:40
There is a Pull Request for teacher module that should fix this issue: https://github.com/vesln/teacher/pull/9
It uses a new URL to call the AtD service.

**Comment by seanmcbreen** [comment] 2016-11-28 23:07
@dwonisch thanks for pointing this out and sorry it took me so long to see this (I was on holiday last week).  I've removed the dependency on `teacher` and re-written that code so I can more easily maintain that code path.  I also adopted the new URI (how did you find that :)).

So a new version of the extension is published - it should work - although I think some of the other URIs are failing e.g. in testing DE was only workign 50% of the tine - the rest of the time I got a `service unavailable message` in HTML.  I don't pop that message up to the user so it's not great.

Thank you.

It would be great if you guys could try it out and see if it's working for you.

**Comment by dwonisch** [comment] 2016-11-28 23:19
Thank you, it is working again :) Awesome work

I found out that the Demo of AtD is using a different URL in it's POST requests http://www.polishmywriting.com/ 

Although I'm not the creator of that PR in teacher repo, looks like someone else figured that out before me.

**Comment by dwonisch** [comment] 2016-11-28 23:26
Seems that German Language is broken now in 0.9.0 and 0.9.1

**Comment by seanmcbreen** [comment] 2016-11-28 23:34
Yes I think it's the service unfortunately - my test harness also fails for de now (whereas it worked until today).  

```
>>>>German Results:>>>>https://de.service.afterthedeadline.com/checkDocument
<?xml version='1.0' encoding='us-ascii'?><results />
>>>>English Results>>>>>https://www.polishmywriting.com/proxy.php?url=/checkDocument
<results>
  <error>
    <string>looook</string>
    <description>Spelling</description>
    <precontext></precontext>
    <suggestions>
        <option>look</option>
        <option>logbook</option>
    </suggestions>
    <type>spelling</type>
    
  </error>
</results>
```

Lets hope it comes back tomorrow.

**Comment by seanmcbreen** [comment] 2016-11-29 18:15
I can confirm even the new URI is not consistently working.

```
>>>>English Results>>>>>https://www.polishmywriting.com/proxy.php?url=/checkDocument
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

There is an interesting PR to allow users to leverage a local AtD server via a setting described here #59.  I probably can't review this today but will look into it - however I fell it will probably not resolve the issues for everyone - as most people will not have there own server.

Sean

**Comment by drpicox** [comment] 2016-11-30 17:06
The same error happens or not randomly if you write the text directly in the input box of http://www.polishmywriting.com/ and then click "Check Writing".

**Comment by jakearchibald** [comment] 2017-02-07 11:23
1.9.0-insider - spell checking hasn't worked in any language for a couple of weeks now. Anything I can do to help debug?

**Comment by seanmcbreen** [comment] 2017-02-07 18:14
I'm afraid the service we use is dead - there really is no work around.  My current thought is to deprecate the extension and suggest people use:

https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

Sorry :(

**Comment by nonoroazoro** [comment] 2017-02-10 07:53
It still doesn't work (OSX VSCode 1.9.1):

`
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:138
Cannot read property 'message' of undefined: TypeError: Cannot read property 'message' of undefined
at SpellProvider.provideCodeActions (/Users/xxxxxxx/.vscode/extensions/seanmcbreen.Spell-0.9.1/out/features/spellProvider.js:85:31)
at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:13:22321
at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:9460
at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:5563)
at Object.f [as asWinJsPromise] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:9423)
at e.provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:13:22275)
at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:13:31778
at t._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:13:28683)
at t.$provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:13:31740)
at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:2729)
`

**Comment by jareis** [comment] 2017-02-17 22:39
Since the the AtD is not working why not change to languagetool? 

https://www.languagetool.org/development/

**Comment by seanmcbreen** [comment] 2017-02-17 22:45
It's a good suggestion and I just checked http://wiki.languagetool.org/public-http-api.  It looks encouraging - however - there are no guarantees, limited access via IP and it's still via HTTPs.

I recently reached out to: https://github.com/Jason-Rev/vscode-spell-checker/issues/69 to suggest I send users there.  That implementation uses local logic and as a result won;t have the same outages.

It does not support non-English checking or grammar however unfortunately.

Sean

**Comment by seanmcbreen** [comment] 2017-04-18 00:17
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean

**Closed by seanmcbreen** 2017-04-18 00:17 UTC
Labels: bug
