### ISSUE TITLE
Adding word to ignore list disables word wrap

### ISSUE THREAD

**Issue by noerw** [Microsoft/vscode-spell-check#38] opened 2016-07-14 17:37 UTC
When adding a word to the ignore list with word-wrap enabled, word-wrap becomes disabled in the process.

**Comment by seanmcbreen** [comment] 2016-08-05 00:18
Wow let me look into that - that will be a bug in VS Code itself.

**Comment by seanmcbreen** [comment] 2016-08-05 00:26
I was unable to reproduce this - could you give it a try with VS Code 1.4 and 1.8.5 of the extension?  If you see the issue LMK we may have to dig in a little more to repro it.

**Comment by noerw** [comment] 2016-09-18 13:37
This still happens for me with current `code 1.5.2` and `spell 0.8.6`.
Also with all other extensions + custom keybindings disabled/removed.
![screencast](https://cloud.githubusercontent.com/assets/7880552/18616076/d45fa6d2-7db5-11e6-89ec-eb131a6a4e8e.gif)

**Comment by alexandrudima** [comment] 2016-09-20 08:17
@bpasero I think the following is happening here and I think it is a VSCode bug around settings:
* toggle word wrap with alt+z
* add a word to the ignore list
  * from looking at the code this writes to a file inside the workspace, at `.vscode\spell.json`
* somehow this triggers the entire workbench to be reconfigured, thus dropping the toggled word wrap

**Comment by bpasero** [comment] 2016-09-20 08:34
@alexandrudima yes, since our configuration service is simply watching all files inside `.vscode` and treats any `*.json` file as a setting file, we actually read in the settings from `spell.json` and add it to the configuration service. I think we should start to think about only supporting `launch.json` and `tasks.json` as standalone setting files besides `settings.json`.

However, doing such a change might break people that today expect to have settings in separate top level files...

**Comment by seanmcbreen** [comment] 2016-09-20 15:46
I manually reload my own settings so don't benefit from the broader watching (I actually need to implement a file watcher for manual updates to be picked up today you need to reload the window).  So my gut feel is that very few people [any people] depend on this.  But we could always provide a small code sample int he release notes to explain how to add a file watcher easily.

**Comment by noerw** [comment] 2016-09-20 18:35
> So my gut feel is that very few people [any people] depend on this. 

well i can't remember to ever have decided to automagically reload my settings or not, so this seems to be default..

Isn't the actual problem here, that the wordwrap-setting is not persistent across reloads?

**Comment by alexandrudima** [comment] 2016-09-20 19:27
@noerw The word wrap setting can be made persistent in the form of editing either the workbench `settings.json` or the user `settings.json` where `wrappingColumn: 0` or `wordWrap: true` will persist it. Otherwise, doing it from the menu is only temporarily (similar how in a diff editor you can switch temporarily to an inline diff)

**Comment by seanmcbreen** [comment] 2016-10-12 15:51
I'll close this issue for now as this is a VS Code issue vs the extension.  The best work arround is what @alexandrudima suggests.

**Closed by seanmcbreen** 2016-10-12 15:51 UTC
Labels: More Info Required
